sonar.projectKey=tutorlink
sonar.projectName=TutorLink
sonar.sourceEncoding=UTF-8

sonar.sources=backend/src/main/java,frontend/src
sonar.tests=backend/src/test/java,frontend/src

sonar.exclusions=**/node_modules/**,**/target/**,**/dist/**,**/coverage/**,**/.scannerwork/**,**/cypress/videos/**,**/cypress/screenshots/**,**/frontend/src/test/**,**/*.test.jsx,**/*.spec.jsx
sonar.test.inclusions=backend/src/test/java/**,frontend/src/**/__tests__/**,frontend/src/**/*.test.jsx,frontend/src/**/*.spec.jsx

sonar.java.binaries=backend/target/classes
sonar.junit.reportPaths=backend/target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
